from __future__ import annotations

from app.models import Component, SectionName


def _section_markup(section: SectionName, component: Component) -> str:
    title = component.name
    description = component.description
    return (
        f"      <section id=\"{section}\" className=\"py-16 border-b border-white/10\">\n"
        f"        <h2 className=\"text-2xl font-semibold\">{title}</h2>\n"
        f"        <p className=\"mt-3 text-slate-300\">{description}</p>\n"
        f"        <p className=\"mt-2 text-sm text-slate-400\">Source: {component.source} ({component.id})</p>\n"
        f"      </section>\n"
    )


def generate_project_files(theme: str, selected_components: dict[SectionName, Component]) -> dict[str, str]:
    section_blocks = "".join(
        _section_markup(section, component)
        for section, component in selected_components.items()
    )

    page = f"""export default function Page() {{
  return (
    <main className=\"min-h-screen {'bg-slate-950 text-slate-100' if theme == 'dark' else 'bg-white text-slate-900'}\">\n      <div className=\"mx-auto max-w-5xl px-6 py-12\">\n{section_blocks}      </div>\n    </main>\n  );
}}
"""

    layout = """import \"./globals.css\";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang=\"en\">
      <body>{children}</body>
    </html>
  );
}
"""

    globals_css = """@tailwind base;
@tailwind components;
@tailwind utilities;
"""

    return {
        "app/page.tsx": page,
        "app/layout.tsx": layout,
        "app/globals.css": globals_css,
        "README.md": "# Generated by ThinnUI AI\n\nRun `npm install && npm run dev`.\n",
    }
